language: rust
rust:
  - nightly
  - beta
  - stable
env:
  global:
    - secure: DLtoi131hH5kOKHzpBB0ZoVDjCWwSiHmTeGaS86ZPx+IHYQzZ6Ll4x/e82SBDG8YGRoOiJUYfatju84ew7Tk9RLK/xvULPJ/WNhSwBK/p9pYWmAl1+QFoaYT3VvsnuIzmIoFjAz6jluBAxvZ5L+pgagayC0BM1Kw83dMS6Ef1LY=
    - MYSQL_SERVER_PASS=""
    - MYSQL_SERVER_PORT="3306"
script:
  - cat ~travis/.my.cnf
  - cargo test && cargo test --no-default-features --features "rustc_serialize" && cargo test --no-default-features --features "ssl"
