env:
  global:
    - secure: NReQ/WsOEMia4t2siHH3dW5CSLewydRzZkrYfR7SC7Pxm/VMOszdmLerEpzXYKpX53bb817m6nSeMDRd4oT1E99miiW4w7LXAsu07XVxbcDMTdkllf2bwXMygb1bZoa5TgX/JcfHgzn7kg5pnU8V1SseXIIAEXNJ6+6qqW3TcAk=
install:
  - curl -O http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xfz rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - (cd rust-nightly-x86_64-unknown-linux-gnu/ && sudo ./install.sh)
  - cd ..
  - git clone https://github.com/rust-lang/cargo
  - git clone https://github.com/wycats/hammer.rs
  - git clone https://github.com/carllerche/hamcrest-rust
  - git clone https://github.com/alexcrichton/toml-rs
  - cd cargo
  - git submodule init
  - git config submodule."libs/hammer.rs".url ../hammer.rs
  - git config submodule."libs/hamcrest-rust".url ../hamcrest-rust
  - git config submodule."libs/toml-rs".url ../toml-rs
  - git submodule update
  - (make && sudo make PREFIX=/usr install)
  - cd ..
before_script:
  - mysql -e 'SET GLOBAL max_allowed_packet=20*1024*1024;'
script:
  - make test doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
