version: 1.0.{build}
branches:
  only:
  - master
clone_folder: c:\clone
environment:
  MYSQL_SERVER_PORT: 3306
  MYSQL_SERVER_PASS: Password12!
  MYSQL_PWD: Password12!
  matrix:
  - TARGET: nightly-x86_64-pc-windows-msvc
  - TARGET: nightly-i686-pc-windows-msvc
  - TARGET: nightly-x86_64-pc-windows-gnu
  - TARGET: nightly-i686-pc-windows-gnu
  - TARGET: beta-x86_64-pc-windows-msvc
  - TARGET: beta-i686-pc-windows-msvc
  - TARGET: beta-x86_64-pc-windows-gnu
  - TARGET: beta-i686-pc-windows-gnu
  - TARGET: 1.26.1-x86_64-pc-windows-msvc
  - TARGET: 1.26.1-i686-pc-windows-msvc
  - TARGET: 1.26.1-x86_64-pc-windows-gnu
  - TARGET: 1.26.1-i686-pc-windows-gnu
    COMPRESS: 1
services: mysql
install:
- cmd: >-
    appveyor DownloadFile https://static.rust-lang.org/dist/rust-%TARGET%.msi

    msiexec /i rust-%TARGET%.msi INSTALLDIR="c:\rust" /qn

    SET PATH=c:\rust\bin;%PATH%
build: off
before_test:
- ps: >-
    $iniPath="C:\ProgramData\MySQL\MySQL Server 5.7\my.ini"

    $newText = ([System.IO.File]::ReadAllText($iniPath)).Replace("# enable-named-pipe", "enable-named-pipe")

    [System.IO.File]::WriteAllText($iniPath, $newText)

    Restart-Service MySQL57

test_script:
- cmd: >-
    "C:\Program Files\MySql\MySQL Server 5.7\bin\mysql" -e "set global max_allowed_packet = 36700160;" --user=root

    SET RUST_BACKTRACE=1

    cargo test && cargo test --no-default-features --features rustc_serialize && cargo test --no-default-features --features ssl
