[package]

name = "mysql"
version = "8.0.0"
authors = ["blackbeam"]
description = "Mysql client library implemented in rust"
license = "MIT"
documentation = "http://blackbeam.org/doc/mysql/index.html"
repository = "https://github.com/blackbeam/rust-mysql-simple"
keywords = ["database", "sql"]
exclude = ["tests/*", ".*", "Makefile"]

[lib]

name = "mysql"
path = "src/lib.rs"

[profile.dev]

opt-level = 0
debug = true

[profile.release]

opt-level = 3
debug = false

[profile.test]

opt-level = 0
debug = true

[profile.bench]

opt-level = 3
debug = false

[profile.doc]

opt-level = 0
debug = true

[features]
default = []
ssl = ["openssl", "security-framework"]
nightly = []

[dependencies]
lazy_static = "~0.2"
time = "~0.1"
bitflags = "~0.7"
byteorder = "~0.5"
url = "^1.1"
bufstream = "~0.1"
fnv = "~1.0"
twox-hash = "~1.0"
chrono = "~0.2"
nom = "~1.2"
uuid = "~0.3"
net2 = "~0.2"
rustc-serialize = "~0.3.22"


[dependencies.regex]
version = "~0.1"
default-features = false

[target.'cfg(not(any(target_os = "windows", target_os = "macos")))'.dependencies.openssl]
version = "~0.7"
optional = true

[target.'cfg(target_os = "macos")'.dependencies.security-framework]
version = "~0.1"
optional = true
features = ["OSX_10_8"]

[target.'cfg(target_os = "windows")'.dependencies.named_pipe]
version = "~0.2"
