[package]

name = "mysql"
version = "0.0.1"
authors = ["blackbeam"]
description = "Mysql client library implemented in rust"
license = "MIT"
exclude = ["tests/*", ".*", "Makefile"]

[lib]

name = "mysql"
crate_type = ["rlib", "dylib"]
path = "src/lib.rs"

[profile.dev]

opt-level = 0
debug = true

[profile.release]

opt-level = 3
debug = false

[profile.test]

opt-level = 0
debug = true

[profile.bench]

opt-level = 3
debug = false

[profile.doc]

opt-level = 0
debug = true

[features]

default = ["ssl"]

ssl = ["openssl"]

[dependencies.lazy_static]
lazy_static = "~0.1.1"

[dependencies.openssl]

git = "https://github.com/sfackler/rust-openssl"
optional = true

[dependencies.time]
time = "~0.0.3"
