[package]

name = "mysql"
version = "11.2.0"
authors = ["blackbeam"]
description = "Mysql client library implemented in rust"
license = "MIT"
documentation = "http://blackbeam.org/doc/mysql/index.html"
repository = "https://github.com/blackbeam/rust-mysql-simple"
keywords = ["database", "sql"]
exclude = ["tests/*", ".*", "Makefile"]

[lib]

name = "mysql"
path = "src/lib.rs"

[profile.dev]

opt-level = 0
debug = true

[profile.release]

opt-level = 3
debug = false

[profile.test]

opt-level = 0
debug = true

[profile.bench]

opt-level = 3
debug = false

[profile.doc]

opt-level = 0
debug = true

[features]
default = []
ssl = ["openssl", "security-framework"]
nightly = []
rustc_serialize = ["rustc-serialize"]

[dev-dependencies]
serde_derive = "~1.0"

[dependencies]
lazy_static = "~0.2"
time = "~0.1"
bitflags = "~0.8"
byteorder = "~1.0"
url = "^1.1"
bufstream = "~0.1"
fnv = "~1.0"
twox-hash = "~1.1"
chrono = "~0.3"
nom = "~3"
uuid = "~0.5"
net2 = "~0.2"

[dependencies.rustc-serialize]
version = "0.3"
optional= true

[dependencies.regex]
version = "~0.2"
default-features = false

[target.'cfg(not(any(target_os = "windows", target_os = "macos")))'.dependencies.openssl]
version = "~0.9"
optional = true

[target.'cfg(target_os = "macos")'.dependencies.security-framework]
version = "~0.1"
optional = true
features = ["OSX_10_8"]

[target.'cfg(target_os = "windows")'.dependencies]
named_pipe = "~0.2"
winapi = "~0.2"
ws2_32-sys = "~0.2"

[target.'cfg(not(feature = "rustc_serialize"))'.dependencies]
serde = "~1.0"
serde_json = "~1.0"

[target.'cfg(unix)'.dependencies]
libc = "~0.2.20"
nix = "~0.8.1"
