[package]

name = "mysql"
version = "2.1.0"
authors = ["blackbeam"]
description = "Mysql client library implemented in rust"
license = "MIT"
documentation = "http://blackbeam.org/doc/mysql/index.html"
repository = "https://github.com/blackbeam/rust-mysql-simple"
keywords = ["database", "sql"]
exclude = ["tests/*", ".*", "Makefile"]

[lib]

name = "mysql"
path = "src/lib.rs"

[profile.dev]

opt-level = 0
debug = true

[profile.release]

opt-level = 3
debug = false

[profile.test]

opt-level = 0
debug = true

[profile.bench]

opt-level = 3
debug = false

[profile.doc]

opt-level = 0
debug = true

[features]
default = ["ssl", "socket"]
ssl = ["openssl"]
socket = ["unix_socket"]
pipe = ["named_pipe"]
nightly = []

[dependencies]
lazy_static = "~0.1.0"
time = "~0.1.0"
bitflags = "~0.4.0"
byteorder = "~0.4.0"
url = "0.5"
bufstream = "0.1"

[dependencies.regex]
version = "~0.1.0"
default-features = false

[dependencies.openssl]
version = "~0.7.4"
optional = true

[dependencies.unix_socket]
version = "~0.5.0"
optional = true

[dependencies.named_pipe]
version = "~0.1.0"
optional = true
