[package]

name = "mysql"
version = "0.6.1"
authors = ["blackbeam"]
description = "Mysql client library implemented in rust"
license = "MIT"
documentation = "http://blackbeam.org/doc/mysql/index.html"
repository = "https://github.com/blackbeam/rust-mysql-simple"
keywords = ["database", "sql"]
exclude = ["tests/*", ".*", "Makefile"]

[lib]

name = "mysql"
path = "src/lib.rs"

[profile.dev]

opt-level = 0
debug = true

[profile.release]

opt-level = 3
debug = false

[profile.test]

opt-level = 0
debug = true

[profile.bench]

opt-level = 3
debug = false

[profile.doc]

opt-level = 0
debug = true

[features]

default = ["ssl"]

ssl = ["openssl"]

[dependencies]
lazy_static = "~0.1.5"
time = "~0.1.11"
regex = "~0.1.9"
regex_macros = "~0.1.4"
bitflags = "0.1"
byteorder = "*"
unix_socket = "0.2.0"

[dependencies.openssl]
version = ">=0.5.0"
optional = true

