[package]
name = "mysql"
version = "16.1.0"
authors = ["blackbeam"]
description = "Mysql client library implemented in rust"
license = "MIT"
documentation = "https://docs.rs/mysql"
repository = "https://github.com/blackbeam/rust-mysql-simple"
keywords = ["database", "sql"]
exclude = ["tests/*", ".*", "Makefile"]
categories = ["database"]
edition = "2018"
build = "build.rs"

[lib]
name = "mysql"
path = "src/lib.rs"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
lto = true

[profile.test]
opt-level = 0
debug = true

[profile.bench]
opt-level = 3
debug = false
lto = true

[features]
nightly = []

[dev-dependencies]
lazy_static = "1.4.0"
rand = "0.7.2"
serde_derive = "1"

[dependencies]
bit-vec = "0.6"
bufstream = "~0.1"
byteorder = "1"
fnv = "1"
io-enum = "0.2.1"
mysql_common = "0.19.1"
native-tls = "0.2.3"
net2 = "~0.2"
percent-encoding = "2.1.0"
regex = { version = "1", default-features = false }
serde = "1"
serde_json = "1"
twox-hash = "1"
url = "2.1"

[target.'cfg(target_os = "windows")'.dependencies]
named_pipe = "~0.4"
winapi = "~0.3"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
nix = "0.15.0"
