[package]

name = "mysql"
version = "0.0.0"
authors = ["blackbeam"]

[lib]

name = "mysql"
crate_type = ["rlib", "dylib"]
path = "src/lib.rs"

[dependencies.lazy_static]

git = "https://github.com/Kimundi/lazy-static.rs"
