[package]
name = "mysql"
version = "17.0.0"
authors = ["blackbeam"]
description = "Mysql client library implemented in rust"
license = "MIT OR APACHE"
documentation = "https://docs.rs/mysql"
repository = "https://github.com/blackbeam/rust-mysql-simple"
keywords = ["database", "sql"]
exclude = ["tests/*", ".*", "Makefile"]
categories = ["database"]
edition = "2018"
build = "build.rs"

[badges]
appveyor = { repository = "blackbeam/rust-mysql-simple", branch = "master", service = "github" }
travis-ci = { repository = "blackbeam/rust-mysql-simple", branch = "master" }

[lib]
name = "mysql"
path = "src/lib.rs"

[profile.bench]
opt-level = 3

[features]
nightly = []

[dev-dependencies]
lazy_static = "1.4.0"
rand = "0.7.2"
serde_derive = "1"

[dependencies]
bufstream = "~0.1"
io-enum = "0.2.1"
lru = "0.4.3"
mysql_common = "0.20.1"
native-tls = "0.2.3"
net2 = "~0.2"
percent-encoding = "2.1.0"
serde = "1"
serde_json = "1"
twox-hash = "1"
url = "2.1"

[target.'cfg(target_os = "windows")'.dependencies]
named_pipe = "~0.4"
winapi = "~0.3"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
nix = "0.17.0"
